version: '3.5'

services:
 crdb:
   image: cockroachdb/cockroach:v19.2.2
   ports:
     - "26257:26257"
     - "8089:8080"
   command: start-single-node --insecure
   restart: always
   volumes:
     - pg-data:/cockroach/cockroach-data

 rabbitmq:
   container_name: rabbitmq
   image: rabbitmq:3.8.12-management
   restart: always
   ports:
     - 5672:5672
     - 15672:15672

 scrapper:
   image: scrapper:f9b928b
   restart: always
   environment:
     - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
   depends_on:
     - rabbitmq
     - crdb

volumes:
  pg-data: